project:
  type: book
  output-dir: docs

date: today
date-format: long

from: markdown+emoji

book:
  title: "User Guide: Preparing FAIR Data"
  author: "Jack Macfadyen"
  page-footer:
    left: "Copyright 2025, Author Name"
  chapters:
    - index.qmd
    - fair-guide.qmd
    - metadata-guide.qmd
    - readme-guide.qmd
    - version-control-guide.qmd
    - references.qmd
  appendices:
    - topic.qmd
    - needs.qmd
    - task-analysis.qmd

bibliography: references.bib

format:
  html:
    toc: true
    highlight-style: a11y
    theme: cosmo
    code-copy: true
  pdf:
    toc: true
    documentclass: scrreprt


