---
title: "The Rhetoric of 'The Role of Statistics in Promoting Data Reusability and Research Transparency'"
editor: visual
author: Jack Macfadyen
bibliography: references.bib
format: pdf
---

# Setting the Stage
In The Role of Statistics in Promoting Data Reusability and Research Transparency, Sarah M. Nusser argues for the inclusion of statistical thinking in order to improve the realm of research and data sharing (@nusser23Role23). Nusser begins the paper by detailing the current environment of expectations from publishers and the scholarly community: the transparency and accessibility of data used by researchers has become increasingly demanded as data reusability has become a necessity in what is considered "good research". By citing real-world examples, such as a project report from the Royal Society that pushes for better data transparency and standards in research (@zotero-13), Nusser both showcases her understanding of the current climate and sets the stage for the topic of new standards for data reusability and how they can be achieved.

# The Argument
The following pages of the paper regard current requirements, recommendations, and practices for striving towards data reusability and research transparency, starting broadly and then becoming more narrow in its scope. Many such examples include the adoption of FAIR Guiding Principles (@zotero-15), the use of repositories (@faniel_yakel14Practices14), and data formatting practices, which are all included to show there are many different strategies implemented for this effort. Nusser's main argument, however, is that the role of statistics is necessary in order to achieve the sort of data reusability for research that the academic community desires. She argues for this by first explaining how reproducibility and replicability is hindered by poor statistical practice, and that proper statistical procedure is the foundation for some of the aforementioned strategies. By introducing the impact that statistical rigor has on the quality of data and replication after topics like data accessibility and reusability, Nusser better highlights for the reader the significance of statistical rigor and how it can undermine many strategies towards reproducibility. She also cites studies that evaluate reproducability and replicability, noting that statistical error is a common factor in hindering data reusability. The inclusion of these references allows Nusser to dive deeper into specific statistical practices that are important in improving the data.

# The Effectiveness
By painting a picture of the changing landscape of research data and reusability as well as recommending actionable strategies towards achieving proper data sharing and transparency, Nusser makes a strong case for why statistics and statistical procedure is vital in achieving this goal. Her argument is clear, based in evidence, and has strong reasoning for why what she recommends should be implemented.

