---
editor: 
  markdown: 
    wrap: 72
---

# Task Analysis {.appendix}

As this user guide will be focused towards researchers, there are
knowledge prerequisites regarding data management and organization,
familiarity with FAIR principles (or at least the concept of data
transparency and reusability), and the ability to create metadata and
documentation of their research. For software, users will be access to a
text editor for README files, a tool for metadata creation, as well as a
slight familiarity with or ability to learn Git and RStudio.

Some basic requirements for the data that the method is used on are
generic, such as being of good quality, having proper documentation, as
well as being in a file format that is open and non-propriety. Missing
values are allowed, but they must be accounted for and explained by a
codebook or other form of documentation. It is necessary that the
researcher is familiar with their own data and is comfortable with
manipulating or handling it so that reusability and transparency are
maximized.

The basic components of the task are as follows:

-   *Planning and organization:* Data must be organized and named
    clearly

-   *Metadata creation:* Create metadata that describes the data's
    context, structure, and origin

-   *Documentation:* Create a README file that includes a description of
    the dataset, instructions on how to use/understand it, details on
    the structure of the data, as well as code used in any data analysis

-   *Data Formatting:* Ensure data is consistent and in a reusable
    format

-   *Version control:* Use version control to track changes to data and
    code

-   *Choosing a repository:* Select a data repository that reflects
    research field and needs. Upload data, metadata, and documentation
    to said repository

When carrying out these tasks, researchers need to be ready to make
decisions that are specific to their own field and research.
Documentation will look different for every researcher, so basic
principles will be described and they will have to make judgment calls.
They will also be responsible for finding the most appropriate
repository for their needs. Theoretically, there will be standards or
popular resources within their field that they can use or draw upon.

One concern about the first draft of the user guide is how it balances
specificity and applicability. The goal is that researchers will be able
to follow the guide and adhere to FAIR principles in accordance with the
sort of research and data that they will be working with.
